---
- hosts: all
  become: yes

  tasks:
  ########################################################################################
  - name: MAIN BLOCK
    block:

    ######################################################################################
    - name: READ STATE FILES
      block:
      - include_tasks: "tasks/read_state.yml"

    ######################################################################################
    - name: BASIC CONFIGURATION
      block:
      - include_role:
          name: slingshot
          
      - include_role:
          name: slingshot_default_packages
      
        ######################################################################################
    - name: INSTALL PACKAGES, MODULES, AND ROLES
      block:
      - name: Install apt packages
        apt:
          update_cache: yes
          name:
          - ettercap-graphical
          - masscan
      
      - include_role:
          name: docker
        vars:
          docker_users:
          - "{{ user_name }}"

      - include_role:
          name: "{{ item }}"
        loop:
        - john

      - include_role:
          name: wordlists
        vars:
          override:
            wordlists_sources:
            - rockyou.txt.zip
       
      - name: Create cmd.sh expect commandlet
        copy:
          dest: /opt/bin/cmd.sh
          mode: 0755
          content: |
            #!/usr/bin/expect
            log_user 0
            set cmd [lindex $argv 0];
            spawn bash
            expect "$ "
            send "$cmd\r"
            interact

      - name: Create menu entries
        copy:
          dest: "{{ appmenu_path }}/{{ item.file }}.desktop"
          mode: 0644
          content: |
            [Desktop Entry]
            Name={{ item.name }}
            GenericName={{ item.generic_name }}
            Comment={{ item.comment }}
            Exec=mate-terminal --command "expect /opt/bin/cmd.sh '{{ item.exec }}'"
            Terminal=false
            Type=Application
            Categories=Slingshot
        loop:
          - { file: 'john', name: 'John', generic_name: 'Password Tool', comment: 'Smart password hash cracker', exec: 'john -h' }
        when: create_appmenu is defined and create_appmenu


    ######################################################################################
    - name: INSTALL DESKTOP
      block:
      - include_role:
          name: mate


